### ISSUE TITLE
Add support for vanilla sign colouring mechanics.

### ISSUE THREAD

**Issue by Pheotis** [stargate-bukkit/Stargate-Bukkit#37]
Traditionally, sign colouring has been handled by external plugins (usually essentials) inserting the `§` symbol into a sign's data.
Thus far, SG has handled coloured gate names as distinct strings;

```
&1gate
&2gate
network
a
```
```
&2gate
&1gate
network
a
```

In modern versions of the game, it has become possible to change a sign's colour (and luminosity) via vanilla mechanics.
These include right-clicking with dye or with glow squid ink.

Currently, such interactions are cancelled by stargate.
It may be a good idea to support them directly.

**Comment by Thorinwasher** [comment]
One problem with this is that there's a setting in the config for a default signcolor. My current solution to solve that conflict is to just check if the color is black, and assume that noone has changed the color of the sign, therefore assigning the default color, which is set from config

**Comment by Pheotis** [comment]
Note to self:

TODO: check compatibility with `freegatesgreen`.
