### ISSUE TITLE
Subpermissions for stargate.use

### ISSUE THREAD

**Issue by Pheotis** [stargate-bukkit/Stargate-Bukkit#56]
Currently, `stargate.use` allows players to activate and enter stargates.

It has been suggested that these could be split into:
`stargate.use.enter` Ability to enter an active stargate (i.e. always on or active by another player)
`stargate.use.activate`Ability to activate a stargate (i.e. making an always-on sign or using the activator).

For backwards compatibility, `stargate.use` will continue to be a general node that grants both of the above subnodes.

**Comment by Thorinwasher** [comment]
A small modification:
You will never want to be only able to activate a gate, but then not have permission to enter it, therefore I propose just adding one more permission; stargate.use.enter
