### ISSUE TITLE
Retcon for config

### ISSUE THREAD

**Issue by Pheotis** [stargate-bukkit/Stargate-Bukkit#58]
The previous config was terrible, and although it was fixed in #54, it will still cause confusion for many users.
Now that the `configVersion` flag has been introduced, adding a retcon for config comments is needed.

**Comment by Thorinwasher** [comment]
Just gonna add that this solution might be a bit messy (asking @Pheotis for his opinion)

Current config is confusing, but this can later be fixed with another script that modifies a normal config file into this
