### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Thorinwasher** [stargate-bukkit/Stargate-Bukkit#73]
As this is a rewrite, the readme.md will need to be redone to include new information and mechanics.

Also, the license should be considered. Concept is @Dinnerbone's, but implementation is from @TheDgtl. The implementation is GNU, but this will not share existing code... can we convert to MPL?

**Comment by Pheotis** [comment]
Going to add updating the wiki to this card; to-do.

- [ ] General (top level) information.
  - [ ] Pitch
  - [ ] Features
- [ ] Usage
  - [ ] Basic Usage
    - [ ] Using Gates
    - [ ] Creating Gates
      - [ ] What are gates
      - [ ] How do gate signs work
    - [ ] Advanced Usage
      - [ ] Gate Flags
      - [ ] Custom Gate Designs (Brief -- ref gatepacks).
- [ ] Setup
  - [ ] Basic Setup
    - [ ] Configuration
    - [ ] Permissions
    - [ ] Installing Gatepacks
  - [ ] Advanced Setup
    - [ ] Custom Gate Designs
    - [ ] Message Customisation
    - [ ] Making Gatepacks
- [ ] Documentation port to discord bot.
- [ ] Figure out license
