### ISSUE TITLE
Gate sign colours (based on type)

### ISSUE THREAD

**Issue by Pheotis** [stargate-bukkit/Stargate-Bukkit#94]

**Comment by Thorinwasher** [comment]
Currently torn between coloring the gatename or the selector. Try both?

**Comment by Pheotis** [comment]
Configuration:

For the selectors (-- / ><)
1. Default sign colour, with the sign's brightness taken into account.
2. The type of the gate (red for private, etc).
3. Neutral grey.

For handling gate names:
1. The selected gate is the colour of the gate's type (red for private, etc), everything else is the default sign colour (w/ brightn.)
2. All gates listed on the sign are the gate's type, with everything else being the default colour.
